import time
import os
from contextlib import contextmanager
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage, ToolMessage
from backend.app.schemas.runs import RunConfig, MessageSchema, TestRunResponse

class RunRunner:
    def __init__(self):
        pass

    @contextmanager
    def _temporary_env(self, env_vars: dict[str, str]):
        if not env_vars:
            yield
            return
        original_env = {}
        for k, v in env_vars.items():
            original_env[k] = os.environ.get(k)
            os.environ[k] = v
        try:
            yield
        finally:
            for k, v in original_env.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v

    def recreate_and_execute_run(self, config: RunConfig) -> TestRunResponse:
        """
        Instantiates the LLM, binds tools, reconstructs messages,
        and invokes the LLM to get the output response and stats.
        """
        with self._temporary_env(config.env_vars or {}):
            # 1. Recreate the LLM client
            llm = self._create_llm_instance(config.model_name, config.temperature)

            # 2. Bind tools if present
            if config.tools:
                try:
                    llm = llm.bind_tools(config.tools)
                except Exception as e:
                    raise ValueError(f"Failed to bind tools to model '{config.model_name}': {str(e)}")

            # 3. Reconstruct messages
            langchain_messages = []
            for index, msg in enumerate(config.messages):
                try:
                    langchain_messages.append(self._map_schema_to_langchain(msg))
                except Exception as e:
                    raise ValueError(f"Failed to parse message at position {index}: {str(e)}")

            # 4. Execute and measure performance
            start_time = time.perf_counter()
            try:
                response = llm.invoke(langchain_messages)
            except Exception as e:
                raise RuntimeError(f"Error during LLM invocation: {str(e)}")
            end_time = time.perf_counter()

            latency_ms = (end_time - start_time) * 1000.0

        # 5. Extract results
        content = response.content or ""
        
        # Extract tool calls generated by the assistant
        tool_calls = []
        if hasattr(response, "tool_calls") and response.tool_calls:
            # response.tool_calls is a list of ToolCall dictionaries:
            # [{'name': '...', 'args': {...}, 'id': '...'}]
            tool_calls = response.tool_calls

        # Extract token usage metadata
        usage = {}
        if hasattr(response, "usage_metadata") and response.usage_metadata:
            # New LangChain standard usage metadata format
            usage = response.usage_metadata
        elif "token_usage" in response.response_metadata:
            usage = response.response_metadata["token_usage"]
        elif getattr(response, "response_metadata", None):
            # General fallback if there is other metadata
            usage = {k: v for k, v in response.response_metadata.items() if "token" in k.lower()}

        return TestRunResponse(
            content=content,
            tool_calls=tool_calls,
            latency_ms=latency_ms,
            usage=usage
        )

    def _create_llm_instance(self, model_name: str, temperature: float):
        """Creates the appropriate LangChain Chat model instance based on model name."""
        from backend.app.services.llm_builder import build_single_llm
        return build_single_llm(model=model_name, temperature=temperature)

    def _map_schema_to_langchain(self, msg: MessageSchema):
        """Converts MessageSchema into the corresponding LangChain message type."""
        content = msg.content
        if isinstance(content, str):
            trimmed = content.strip()
            if (trimmed.startswith("[") and trimmed.endswith("]")) or (trimmed.startswith("{") and trimmed.endswith("}")):
                try:
                    import json
                    content = json.loads(trimmed)
                except Exception:
                    pass

        role = msg.role.lower()
        if role == "system":
            return SystemMessage(content=content, name=msg.name)
        elif role in ["human", "user"]:
            return HumanMessage(content=content, name=msg.name)
        elif role in ["ai", "assistant"]:
            # Set tool_calls if any were generated in this step
            return AIMessage(
                content=content, 
                name=msg.name, 
                tool_calls=msg.tool_calls or []
            )
        elif role == "tool":
            if not msg.tool_call_id:
                raise ValueError("Tool messages must contain a tool_call_id.")
            return ToolMessage(
                content=content, 
                name=msg.name, 
                tool_call_id=msg.tool_call_id
            )
        else:
            # Fallback to general ChatMessage
            from langchain_core.messages import ChatMessage as LcChatMessage
            return LcChatMessage(content=content, role=msg.role, name=msg.name)
