from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional, Union

class MessageSchema(BaseModel):
    role: str = Field(..., description="Role of the message author (system, human/user, ai/assistant, tool)")
    content: Union[str, List[Any], Dict[str, Any]] = Field("", description="The text content or multimodal content blocks of the message")
    name: Optional[str] = Field(None, description="Optional name for the message author")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Optional tool calls generated by the assistant")
    tool_call_id: Optional[str] = Field(None, description="Optional tool call ID for tool role messages")

class ToolSchema(BaseModel):
    type: str = Field("function", description="Type of the tool (typically 'function')")
    function: Dict[str, Any] = Field(..., description="The function definition containing name, description, and parameters")

class RunConfig(BaseModel):
    run_id: Optional[str] = Field(None, description="The LangSmith run ID if downloaded")
    model_name: str = Field("gpt-4o-mini", description="The identifier of the LLM model")
    temperature: Optional[float] = Field(None, description="The sampling temperature (0.0 to 2.0)")
    messages: List[MessageSchema] = Field(default_factory=list, description="Ordered list of conversation messages")
    tools: List[Dict[str, Any]] = Field(default_factory=list, description="List of tools bound to the model")
    env_vars: Optional[Dict[str, str]] = Field(default_factory=dict, description="Environment variables to set temporarily for the run")
    max_tokens: Optional[int] = Field(None, description="The maximum number of tokens to generate")
    thinking_mode: Optional[str] = Field("default", description="Thinking mode ('default', 'disabled', 'adaptive', 'enabled')")
    thinking_effort: Optional[str] = Field("", description="Thinking effort ('low', 'medium', 'high' or budget tokens)")
    baseline_output: Optional[str] = Field(None, description="The original output from LangSmith")
    baseline_latency_ms: Optional[float] = Field(None, description="The original latency in milliseconds")
    baseline_token_usage: Optional[Dict[str, Any]] = Field(None, description="The original token usage details")

class FetchRequest(BaseModel):
    run_id: str = Field(..., description="The unique LangSmith run ID to download")

class TestRunResponse(BaseModel):
    content: Union[str, List[Any], Dict[str, Any]] = Field(..., description="Response content returned by the LLM")
    tool_calls: List[Dict[str, Any]] = Field(default_factory=list, description="Tool calls generated during the run")
    latency_ms: float = Field(0.0, description="Execution time in milliseconds")
    usage: Dict[str, Any] = Field(default_factory=dict, description="Token usage details (prompt, completion, total tokens)")
    backup_path: Optional[str] = Field(None, description="Path to the raw response backup file")

class BulkDeleteRequest(BaseModel):
    run_ids: List[str] = Field(..., description="List of unique LangSmith run IDs to delete")

